project_id = "onksarfyxnfjlmodfcvo"

[api]
enabled = true
port = 54321

[db]
port = 54322

[functions.generate-video-plan]
verify_jwt = false

[functions.analyze-video]
verify_jwt = false

[functions.generate-asset]
verify_jwt = false

[functions.generate-remotion-code]
verify_jwt = false

[functions.render-video]
verify_jwt = false

[functions.render-webhook]
verify_jwt = false

[functions.upload-video]
verify_jwt = false

[functions.firecrawl-brand]
verify_jwt = false

[functions.edit-video-plan]
verify_jwt = false
